### ISSUE TITLE
All FIMS Query Excel downloads are including IndoPacific info

### ISSUE THREAD

**Issue by MikeTrizna** [biocodellc/biocode-fims#105]
I just downloaded a spreadsheet from the Barcode of Wildlife Mexico project on FIMS, and it includes extra worksheets "Instructions", "Data Fields", and "Lists". The Instructions worksheet has a title "indoPacificTemplate", so I think that's the project it is pulling from.

Here's a Dropbox link to an example: https://www.dropbox.com/s/4yb78dt6ayubzsa/fims_download_example.xlsx?dl=0

**Comment by jdeck88** [comment]
Fixed by commit earlier today and just now deployed.
