### ISSUE TITLE
When managing expeditions, click events fail

### ISSUE THREAD

**Issue by tigerhawkvok** [biocodellc/biocode-fims#107]
While I'm bug reporting, here's a pretty minor one: -- click events fail on the expedition page. The first expansion works, but you can't view any details for a given expedition.

Here's a video:

[fims-expedition-click-event.zip](https://github.com/biocodellc/biocode-fims/files/886691/fims-expedition-click-event.zip)

**Comment by jdeck88** [comment]
This issue was moved to biocodellc/biscicol-fims#30
