### ISSUE TITLE
Add fields to individual sample data pages

### ISSUE THREAD

**Issue by tweedts** [biocodellc/biocode-fims#108]
In our project, samples are assigned a multiple unique identifiers, e.g. an SI field number, a USNM catalog number, and a NOAA specimen number.
Moving forward, it is going to be important that individuals looking up specimens can view all the various catalog numbers assigned to the same specimen so they could cross reference or navigate to the USNM collections database when browsing. 
Please add the following fields to be visible on the individual sample data pages:
voucherCatalogNumber
voucherURI
catalogNumber
otherCatalogNumber

**Comment by tweedts** [comment]
Please also add tissueType as a field that appears on a materialSample page next to the child tissues.

**Comment by jdeck88** [comment]
now living at  https://github.com/biocodellc/geome-ui/issues/623
