### ISSUE TITLE
Add Plate/Well & Taxonomy information to configuration file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [biocodellc/biocode-fims#14]
```
This will make it so we don't have to fill in all of the information on the 
biocode plugin.

Let Matthew know when this is done.


```

Original issue reported on code.google.com by `jdec...@gmail.com` on 7 Feb 2014 at 11:05

**Comment by jdeck88** [comment]
This has been completed for CBOL/BWP -- if other project configurations need this, i can add it for them specifically. Closing.
