### ISSUE TITLE
Logging in using 2-factor FIMS authentatication, gives error popup

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-fims#93]
The 2-factor login process appears to work.

However, after doing this, a popup appears that says "invalid_request Please contact your system administrator.".   This appears when testing in the DEV environment on port 8179 and the user is redirected to the port 80 environment after the succesfull login.   So, somewhere there is a hard-coded redirect to the root direct and the port is not specified.

**Comment by rodney757** [comment]
This was actually a bcid error. Fixed in bcid commit 434745287123a630f5c8035c5827510fc3ed9dc4
