### ISSUE TITLE
Lost State for loaded spreadsheet when working with validation options.

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-fims#95]
The validation page of the FIMS seems to "forget" the spreadsheet has been loaded when the Upload and Final checkboxes are checked after already validating.  

This requires the user has to refresh the page and reload the spreadsheet.

**Comment by rodney757** [comment]
It appears to be keeping the state when I try. I tried with chrome and firefox. First validating and then uploading and I don't have to re-select the sheet.

**Comment by rodney757** [comment]
also tried locally and on nmnh dev

**Comment by jdeck88** [comment]
This appears to be fixed, closing.
